mkdir test
mkdir test/test
mkdir test/test/titi
mkdir test/titi
mkdir test/titi/test

touch "./test/#1#"
touch "./test/#et#"
touch "./test/.7~"
touch "./test/1~"
touch "./test/disdonc~"
touch "./test/test/#2#"
touch "./test/test/2~"
touch "./test/test/titi/#4#"
touch "./test/test/titi/4~"
touch "./test/titi/#3#"
touch "./test/titi/3~"
touch "./test/titi/test/#5#"
touch "./test/titi/test/5~"
